sudo: required
services:
  - docker

# Here we can add more steps to build other Docker images to run tests for other components as wlel
before_install:
  - docker build -t mbezyan/react-test -f ./client/Dockerfile.dev ./client

# This is where tests will be executed
# Here we can add more steps for testing other components
script:
  - docker run -e CI=true mbezyan/react-test npm test

# Here we build images for Production version of each component
after_success:
  - docker build -t mbezyan/multi-client ./client
  - docker build -t mbezyan/multi-nginx ./nginx
  - docker build -t mbezyan/multi-server ./server
  - docker build -t mbezyan/multi-worker ./worker
  # Log in to the Docker CLI
  # echo "$DOCKER_PASSWORD" retrieves DOCKER_PASSWORD environment variable, and emits it on Standard In as intpu to the next
  # command which is 'docker login -u ...' which is to ld to expect to receive it from Standard In
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all the images that we have built and push to Docker Hub
  - docker push mbezyan/multi-client
  - docker push mbezyan/multi-nginx
  - docker push mbezyan/multi-server
  - docker push mbezyan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-329052544356
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
