version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  api: # this refers to the stuff in server and we changed the name to avoid conflicts in Nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true # This is to rectify a bug which was introduced with the latest Create React App version that is causing the React app to exit when starting with Docker Compose.
  worker: # we don't want worker to automatically start back up if an issue occurs
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always # we want this to always be running no matter what
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80" # Map 3050 on the machine running Docker to port 80 in the running instance
    depends_on:
      - api
      - client
