apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-k8s-hash-bez-com-tls
spec:
  # This specifies where the Certificate should be stored
  # after it's obtained from Cert Manager.
  secretName: multi-k8s-hash-bez-com
  issuerRef:
    # This should correspond to the corresponding Issuer configuration
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.hash-bez.com
  # List of all the different domains that should be associated
  # with the Certificate. i.e. The Certificate we get back will
  # be good for multi-k8s.hash-bez.com
  dnsNames:
    - multi-k8s.hash-bez.com
  # Commenting out the following becuase acme is not recognised in this apiVersion
  #acme:
  #  config:
  #    - http01:
  #        ingressClass: nginx
  # These are the domain names that will be used in the
  # verification process.
  #      domains:
  #        - multi-k8s.hash-bez.com
